FROM golang:1.7

RUN apt-get -qq update
RUN apt-get install -y libsystemd-journal-dev

RUN mkdir -p /go/src/github.com/kubernetes-incubator/
COPY . /go/src/github.com/kubernetes-incubator/rktlet/
WORKDIR /go/src/github.com/kubernetes-incubator/rktlet/journal2cri

VOLUME ["/go/src/github.com/kubernetes-incubator/rktlet/journal2cri/bin"]

CMD make
