/*
Copyright 2016 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by Mockery for Init. This code should not be edited by hand
package mocks

import "github.com/stretchr/testify/mock"

// Init is an autogenerated mock type for the Init type
type Init struct {
	mock.Mock
}

// StartProcess provides a mock function with given fields: cgroupParent, command, args
func (_m *Init) StartProcess(cgroupParent string, command string, args ...string) (string, error) {
	ret := _m.Called(cgroupParent, command, args)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string, ...string) string); ok {
		r0 = rf(cgroupParent, command, args...)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, ...string) error); ok {
		r1 = rf(cgroupParent, command, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
